---

- name: "(Handler) Restart taniumclient.service"
  ansible.builtin.systemd_service:
    name: taniumclient.service
    state: restarted
    daemon_reload: yes
  listen: restart-taniumclient-service
