---

- name: Ensure additional packages are present
  ansible.builtin.apt:
    name:
      - ldap-utils
      - sssd-ldap
    state: present

- name: "Apply Kdcinfo file for: {{ krb5_realm | upper }}"
  ansible.builtin.template:
    src: "var/lib/sss/pubconf/kdcinfo.xxxx.j2"
    dest: "/var/lib/sss/pubconf/kdcinfo.{{ krb5_realm | upper }}"
    owner: root
    group: root
    mode: '0664'
    backup: true
  notify: restart-sssd-service

- name: Apply krb5 config file
  ansible.builtin.template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0664'
    backup: true
  notify: restart-sssd-service

- name: Apply primary sssd config file
  ansible.builtin.template:
    src: etc/sssd/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
    backup: true
  notify: restart-sssd-service

- name: Set custom access.conf facts
  ansible.builtin.set_fact:
    access_conf_expr: |-
      +:gdm:LOCAL
      {% for group in ssh_allow_groups %}
      +:@{{ group }}:ALL
      {% endfor %}
      +:ALL:cron
      -:ALL EXCEPT ({{ ssh_admin_group }}) (wheel) root:ALL

- name: Add default access.conf lines
  ansible.builtin.blockinfile:
    path: /etc/security/access.conf
    block: "{{ access_conf_expr }}"
    create: false
    insertafter: EOF

- name: Enable automatic home directory creation
  ansible.builtin.shell:
    cmd: /usr/sbin/pam-auth-update --enable mkhomedir
  args:
    executable: /bin/bash
  changed_when: true

- name: Unmask, start, and enable sssd.service
  ansible.builtin.systemd_service:
    name: sssd.service
    state: started
    masked: false
    enabled: true
