---

- name: Ensure that firewalld package is present
  ansible.builtin.apt:
    name: firewalld
    state: present

- name: Ensure zone drifting is disabled
  community.general.ini_file:
    path: /etc/firewalld/firewalld.conf
    option: AllowZoneDrifting
    value: "no"
    mode: '0644'
  notify: reload-firewalld-service

- name: (Management-only) Apply firewall ports for Ubuntu autoinstall artifacts
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" port protocol="tcp" port=9000 source address="{{ proxmox_vm_cidr }}" accept
    permanent: true
    state: enabled
  delegate_to: "{{ item }}"
  loop: "{{ groups['ndp_management'] }}"

- name: Unmask, start and enable firewalld.service
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: started
    enabled: true
    masked: false
