---

- name: (Debugging) Display local Ansible LVM facts
  ansible.builtin.debug:
    msg: "{{ ansible_lvm }}"
    verbosity: 3

- name: Grow /dev/sda3 to fill all available space
  ansible.builtin.shell:
    cmd: /usr/bin/growpart /dev/sda 3
  args:
    executable: /bin/bash
  register: growpart_result
  changed_when:
    - growpart_result['rc'] < 1
    - "'CHANGED' in growpart_result['stdout']"
  failed_when:
    - growpart_result['rc'] > 0
    - "not 'NOCHANGE' in growpart_result['stdout']"

- name: Extend the logical volume and resize the filesystem
  when: "not 'NOCHANGE' in growpart_result['stdout']"
  ansible.builtin.shell:
    cmd: |-
      /usr/sbin/lvextend -r -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
  args:
    executable: /bin/bash
  register: lvextend_result
  changed_when:
    - lvextend_result['rc'] < 1
    - "not 'unchanged from' in lvextend_result['stdout']"
    - "not 'Nothing to do!' in lvextend_result['stderr']"
