---

- name: (Debugging) Display local Ansible LVM facts
  ansible.builtin.debug:
    msg: "{{ ansible_lvm }}"
    verbosity: 3

- name: Extend the logical volume and resize the filesystem
  ansible.builtin.shell:
    cmd: |-
      /usr/sbin/lvextend -r -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
  args:
    executable: /bin/bash
  register: lvextend_result
  changed_when:
    - lvextend_result['rc'] < 1
    - "not 'unchanged from' in lvextend_result['stdout']"
    - "not 'Nothing to do!' in lvextend_result['stderr']"
