---

- name: Adjust DNS domains not populated by DHCP
  community.general.ini_file:
    path: /etc/systemd/resolved.conf
    section: Resolve
    option: Domains
    value: "{{ dns_domains | join(' ') }}"
    state: present
    create: false
  notify: restart-resolved-service
