---
- name: Regenerate Packer user-data File
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - name: Calculate password hash
      ansible.builtin.shell:
        cmd: /usr/bin/openssl passwd -6 "{{ ansible_password }}"
      args:
        executable: /bin/bash
      changed_when: yes
      register: password_hash

    - name: Regenerate Packer user-data File    # noqa no-relative-paths
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/user-data.j2"
        dest: "{{ playbook_dir }}/../../packer/ubuntu-server-noble/http/user-data"
        mode: '0644'
