---

- name: "Provision: All NDP VMs"
  hosts: ndp_management,ndp_vms
  become: yes
  gather_facts: yes

  tasks:
    - name: Configure firewall
      ansible.builtin.include_role:
        name: provision
        tasks_from: firewall

    - name: Configure physical partitions and logical volumes/groups 
      ansible.builtin.include_role:
        name: provision
        tasks_from: resize-lvm

    - name: Set the static hostname
      ansible.builtin.command: >-
        /usr/bin/hostnamectl --static set-hostname {{ inventory_hostname }}
      changed_when: no

    - name: Configure DNS 
      ansible.builtin.include_role:
        name: provision
        tasks_from: resolved

    - name: Update and upgrade existing apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes

    - name: Ensure additional packages are present
      ansible.builtin.apt:
        name:
          - bind9-dnsutils
          - iputils-ping
          - ldap-utils
          - sssd-ldap
          - tlslookup
          - vim
        state: present

    - name: Install additional snaps
      when: snaps is defined
      community.general.snap:
        name: "{{ snap['name'] }}"
        classic: "{{ snap['classic'] | default(omit) }}"
        channel: "{{ snap['channel'] | default(omit) }}"
        state: present
      loop: "{{ snaps }}"
      loop_control:
        label: "{{ snap['name'] }}"
        loop_var: snap
    
    - name: Configure campus authentication 
      ansible.builtin.include_role:
        name: provision
        tasks_from: campus-auth

    - name: "Update password for the local admin account: {{ local_admin_user }}"
      ansible.builtin.user:
        name: "{{ local_admin_user }}"
        password: "{{ local_admin_password | password_hash('sha512', 'mysecretsalt') }}"

    - name: Configure sudoers
      ansible.builtin.include_role:
        name: provision
        tasks_from: sudoers

- name: "Provision: Management NDP VMs"
  hosts: ndp_management
  become: yes
  gather_facts: yes

  tasks:
    - name: Install and configure HashiCorp Packer
      ansible.builtin.include_role:
        name: packer_install

    - name: Ensure additional packages are present
      ansible.builtin.apt:
        name:
          - make
          - python3.12-venv
          - sshpass
        state: present

    - name: Apply firewall ports for Ubuntu autoinstall artifacts
      ansible.posix.firewalld:
        rich_rule: rule family="ipv4" port protocol="tcp" port=9000 source address="{{ proxmox_vm_cidr }}" accept
        permanent: true
        state: enabled
      register: firewalld_update

    - name: (Should be Handler) Reload the firewalld config
      when: firewalld_update['changed'] | bool
      ansible.builtin.shell:
        cmd: /usr/bin/firewall-cmd --reload
      args:
        executable: /bin/bash