---

- name: Ensure that the firewalld (and related) packages are present
  ansible.builtin.apt:
    name:
      - firewalld
      - python3-dbus
      - python3-firewall
    state: present

- name: Ensure zone drifting is disabled
  community.general.ini_file:
    path: /etc/firewalld/firewalld.conf
    option: AllowZoneDrifting
    value: "no"
    mode: '0644'
  notify: reload-firewalld-service

- name: Unmask, start and enable firewalld.service
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: started
    enabled: true
    masked: false

- name: (Hack) Always allow SSH from extra host
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" port protocol="tcp" port=ssh source address="{{ extra_host }}" accept
    permanent: true
    immediate: true
    state: enabled

- name: (Workers-only) Allow SSH from NDP management host
  when: inventory_hostname in groups['ndp_vms']
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" port protocol="tcp" port=ssh source address="{{ ndp_mgmt_ipv4 }}" accept
    permanent: true
    immediate: true
    state: enabled

- name: (Management-only) Allow SSH from extra IP sets
  when: inventory_hostname in groups['ndp_management']
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" port protocol="tcp" port=ssh source address="{{ item }}" accept
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ firewall_trusted_ipsets }}"

- name: Ensure SSH service is not enabled without restriction
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: true
    state: absent

- name: Apply firewall ports for the Prometheus Node Exporter
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" port protocol="tcp" port=9100 source address="{{ monitoring_cidr }}" accept
    permanent: true
    immediate: true
    state: enabled

- name: Apply firewall ports for additional services
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ firewall_ports }}"
