---

- name: Ensure that the firewalld (and related) packages are present
  ansible.builtin.apt:
    name:
      - firewalld
      - python3-dbus
      - python3-firewall
    state: present

- name: Ensure zone drifting is disabled
  community.general.ini_file:
    path: /etc/firewalld/firewalld.conf
    option: AllowZoneDrifting
    value: "no"
    mode: '0644'
  notify: reload-firewalld-service

- name: Unmask, start and enable firewalld.service
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: started
    enabled: true
    masked: false

# - name: (Management-only) Apply firewall ports for additional services
#   when: inventory_hostname in groups['ndp_management']
#   ansible.posix.firewalld:
#     rich_rule: rule family="ipv4" port protocol="tcp" port=xxxx source address="{{ proxmox_vm_cidr }}" accept
#     permanent: true
#     immediate: true
#     state: enabled

- name: Apply firewall ports for the Prometheus Node Exporter
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" port protocol="tcp" port=9100 source address="{{ monitoring_cidr }}" accept
    permanent: true
    immediate: true
    state: enabled

- name: (Workers-only) Apply public firewall TCP ports for additional services
  when: inventory_hostname in groups['ndp_vms']
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 80
    - 443
    - 5200
    - 5201
    - 8080
