---
- name: Remove NDP production VMs
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Remove production VMs
      community.proxmox.proxmox_kvm:
        # Connection config
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        node: "{{ hostvars[item]['proxmox_node'] }}"
        timeout: 3000

        vmid: "{{ hostvars[item]['vm_id'] }}"
        state: absent
      loop: "{{ ndp['prod'] }}"
