---

- name: Create new NDP VMs
  hosts: 127.0.0.1
  connection: local
  serial: 1
  gather_facts: false

  tasks:
    - name: Retrieve information about specific VM by ID
      vars:
        new_vm_id: "{{ hostvars[item]['vm_id'] }}"
      community.general.proxmox_vm_info:
        api_host: "{{ proxmox_api_host }}"
        # api_token_id: "{{ proxmox_api_token_id }}"
        # api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        type: qemu
        vmid: "{{ new_vm_id }}"
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"
      register: current_vms_info

    - name: Set additional facts
      ansible.builtin.set_fact:
        current_vms: "{{ (current_vms_info['results'] | map(attribute='proxmox_vms')) | flatten | map(attribute='vmid') }}"

    - name: Create new VMs
      when: not hostvars[item]['vm_id'] in current_vms
      vars:
        vm_id: "{{ hostvars[item]['vm_id'] }}"
        vm_mac_addr: "{{ hostvars[item]['vm_network_adapters_mac_address'] }}"
        vm_storage_pool: "{{ hostvars[item]['proxmox_storage_pool'] }}"
      community.general.proxmox_kvm:
        # Connection configuration
        api_host: "{{ proxmox_api_host }}"
        # api_token_id: "{{ proxmox_api_token_id }}"
        # api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        timeout: 3000

        # Location Configuration
        name: "{{ hostvars[item]['inventory_hostname'] }}"
        vmid: "{{ vm_id }}"

        # Hardware Configuration
        cpu: host
        sockets: "{{ hostvars[item]['vm_cpu_sockets'] }}"
        cores: "{{ hostvars[item]['vm_cpu_cores'] }}"
        memory: "{{ hostvars[item]['vm_memory'] }}"

        # Boot Configuration
        bios: ovmf
        boot: "order=scsi0"
        # bootdisk: scsi0
        efidisk0:
          storage: "{{ vm_storage_pool }}"
          format: raw
          efitype: 4m
          pre_enrolled_keys: false

        # VM Configuration
        agent: true
        cicustom: "user=local:snippets/{{ vm_id }}-user-data.yml"
        cipassword: "{{ ansible_password }}"
        citype: nocloud
        ciuser: "{{ ansible_user }}"
        ide:
          ide2: "{{ hostvars[item]['proxmox_storage_pool'] }}:cloudinit"
        ipconfig:
          ipconfig0: 'ip=dhcp'
        net:
          net0: 'virtio={{ vm_mac_addr }},bridge=vmbr1,tag=1702'
        node: "{{ hostvars[item]['proxmox_node'] }}"
        ostype: l26
        scsi:
          scsi0: "{{ vm_storage_pool }}:0,import-from=/var/lib/vz/template/iso/ubuntu-24.04-server-cloudimg-amd64.img"
        scsihw: virtio-scsi-pci
        serial:
          serial0: socket
        sshkeys: "{{ ci_ssh_key }}"
        vga: serial0
      register: created_vms
      # until: created_vms is not failed
      # retries: 10
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"

    - name: Resize disks
      when:
        - created_vms['changed']
        - hostvars[item]['vm_id'] in (created_vms['results'] | map(attribute='vmid'))
      # when: hostvars[item]['vm_id'] in created_vm_ids
      community.general.proxmox_disk:
        # Connection configuration
        api_host: "{{ proxmox_api_host }}"
        # api_token_id: "{{ proxmox_api_token_id }}"
        # api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        timeout: 3000

        # Location configuration
        vmid: "{{ hostvars[item]['vm_id'] }}"

        # Disk configuration
        disk: scsi0
        size: "{{ hostvars[item]['vm_os_disk_size'] }}"
        state: resized
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"

    - name: Ensure VMs are started
      vars:
        new_vm_id: "{{ hostvars[item]['vm_id'] }}"
      community.general.proxmox_kvm:
        # Connection configuration
        api_host: "{{ proxmox_api_host }}"
        # api_token_id: "{{ proxmox_api_token_id }}"
        # api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        timeout: 3000

        # Location configuration
        vmid: "{{ new_vm_id }}"
        state: started
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"
