---

- name: Create new NDP VMs
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Retrieve information about specific VM by ID
      vars:
        new_vm_id: "{{ hostvars[item]['vm_id'] }}"
      community.general.proxmox_vm_info:
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        type: qemu
        vmid: "{{ new_vm_id }}"
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"
      register: current_vms_info

    - name: Set additional facts
      ansible.builtin.set_fact:
        current_vms: "{{ (current_vms_info['results'] | map(attribute='proxmox_vms')) | flatten | map(attribute='vmid') }}"

    - name: Create but do not start VMs
      # check_mode: yes
      when: not hostvars[item]['vm_id'] in current_vms
      vars:
        vm_disk_size: "{{ hostvars[item]['vm_os_disk_size'] | regex_search('\\d+') }}"
        vm_mac_addr: "{{ hostvars[item]['vm_network_adapters_mac_address'] }}"
        vm_storage_pool: "{{ hostvars[item]['proxmox_storage_pool'] }}"
      community.general.proxmox_kvm:
        # Connection configuration
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        timeout: 3000

        # Location Configuration
        name: "{{ hostvars[item]['inventory_hostname'] }}"
        vmid: "{{ hostvars[item]['vm_id'] }}"

        # Boot Configuration
        bios: ovmf
        bootdisk: scsi0
        efidisk0:
          storage: "{{ vm_storage_pool }}"
          format: raw
          efitype: 4m
          pre_enrolled_keys: false

        # Hardware Configuration
        cpu: host
        sockets: 1
        cores: 2
        memory: 4096

        # # CloudInit Configuration
        # citype: nocloud
        # cicustom: "{{ cicustom }}"

        # VM Configuration
        agent: true
        format: raw
        ide:
          ide2: "{{ hostvars[item]['proxmox_storage_pool'] }}:cloudinit,format=raw"
        ipconfig:
          ipconfig0: 'ip=dhcp'
        net:
          net0: 'virtio={{ vm_mac_addr }},bridge=vmbr1,tag=1702'
        node: "{{ hostvars[item]['proxmox_node'] }}"
        ostype: l26
        scsi:
          scsi0: '{{ vm_storage_pool }}:{{ vm_disk_size }},iothread=1,discard=on,import-from=/var/lib/vz/template/iso/ubuntu-24.04.2-live-server-amd64.iso,format=raw'
        scsihw: virtio-scsi-pci
        storage: "{{ vm_storage_pool }}"
        vga: std
      register: created_vms
      # until: created_vms is not failed
      # retries: 10
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"

    - name: Set additional facts
      ansible.builtin.set_fact:
        created_vm_ids: "{{ created_vms['results'] | selectattr('changed') | map(attribute='vmid') }}"

    - name: Only forcibly update cloud-init for newly created VMs
      when: hostvars[item]['vm_id'] in created_vm_ids
      vars:
      community.general.proxmox_kvm:
        # Connection configuration
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_user: "{{ proxmox_api_user }}"
        timeout: 3000

        # Location Configuration
        vmid: "{{ hostvars[item]['vm_id'] }}"

        # VM Configuration
        citype: nocloud
        cicustom: "user=local:snippets/{{ hostvars[item]['vm_id'] }}-user-data.yml"
        node: "{{ hostvars[item]['proxmox_node'] }}"
        update: true

      register: ci_enabled_vms
      # until: ci_enabled_vms is not failed
      # retries: 10
      loop: "{{ groups['ndp_management'] + groups['ndp_vms'] }}"

    - name: Set additional facts
      ansible.builtin.set_fact:
        ci_enabled_vm_ids: "{{ ci_enabled_vms['results'] | selectattr('changed') | map(attribute='vmid') }}"
